### ISSUE TITLE
no such param - extraCertificateOptions={'nextProtocols': [b'h2']} 

### ISSUE THREAD

**Issue by aidylewis** [python-hyper/hyper-h2#254]
Reproducer 

```
$ git clone https://github.com/python-hyper/hyper-h2
$ pyenv local 3.5.1
$ python examples/twisted/head_request.py
```

https://github.com/python-hyper/hyper-h2/blob/master/examples/twisted/head_request.py#L104

Is there a specific version of Twisted, I need to use? 

Thank You

**Comment by Lukasa** [comment]
Ugh, that's just out of date: it should be `acceptableProtocols`, not `nextProtocols`, I think. That example was written against a pre-release version of Twisted, and the APIs got renamed.

In fact, the whole thing should change. The `post_request` example shows the correct invocation. The `head_request` also has the wrong check for the negotiated protocol in its `dataReceived`: again, the `post_request` shows how to do this correctly.

Are you interested in providing a PR to fix this up?

**Comment by aidylewis** [comment]
> Are you interested in providing a PR to fix this up?

Of course.

**Comment by aidylewis** [comment]
i've made the two changes you've suggested above

```diff
     def dataReceived(self, data):
         if not self.known_proto:
-            self.known_proto = self.transport.getNextProtocol()
+            self.known_proto = self.transport.negotiatedProtocol
             assert self.known_proto == b'h2'

         events = self.conn.receive_data(data)
@@ -101,7 +101,7 @@ class H2Protocol(Protocol):

 options = optionsForClientTLS(
     hostname=AUTHORITY,
-    extraCertificateOptions={'nextProtocols': [b'h2']},
+    acceptableProtocols=[b'h2'],
 )
```

But do we also need also to change the conditional in ```dataReceived``` (```head_request.py``` uses ```event.stream_id```) and implement a ```connectionLost``` interface?

**Comment by Lukasa** [comment]
We don't need to change the `dataReceived` conditional: the differences are just cosmetic. `stream_id` is unused in the `head_request`, so we could safely remove it. But it's up to you. 

We also don't need `connectionLost`: we have it in `post_request` to do cleanup of the file object. But we could have it, again, if you wanted it.

**Comment by aidylewis** [comment]
The connection is being made and the remote settings are being updated.

```
<RemoteSettingsChanged changed_settings:{3: ChangedSetting(setting=3, original_value=None, new_value=100), 4: ChangedSetting(setting=4, original_value=65535, new_value=16777216)}>
```

But we don't receive any data

```
h2.exceptions.InvalidBodyLengthError: InvalidBodyLengthError: Expected 11729 bytes, received 0
```

```post_request.py``` runs beautifully.

**Comment by aidylewis** [comment]
Changing
```self.conn.send_headers(1, request_headers, end_stream=True)```
to
```self.conn.send_headers(1, request_headers)```

Returns
```
<ConnectionTerminated error_code:0, last_stream_id:1, additional_data:69646c652074696d656f7574>
```

I assume error_code: 0 is good.

**Comment by Lukasa** [comment]
Heh, can you provide the full traceback? I think there is code in H2 that doesn't handle HEAD responses with Content-Length set properly.

**Comment by aidylewis** [comment]
```
$ hyper-h2 python examples/twisted/head_request.py
<RemoteSettingsChanged changed_settings:{3: ChangedSetting(setting=3, original_value=None, new_value=100), 4: ChangedSetting(setting=4, original_value=65535, new_value=16777216)}>
Unhandled Error
Traceback (most recent call last):
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/protocols/tls.py", line 430, in dataReceived
    self._flushReceiveBIO()
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/protocols/tls.py", line 400, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 115, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "examples/twisted/head_request.py", line 50, in dataReceived
    events = self.conn.receive_data(data)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h2/connection.py", line 1299, in receive_data
    events.extend(self._receive_frame(frame))
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h2/connection.py", line 1322, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h2/connection.py", line 1497, in _receive_data_frame
    flow_controlled_length
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h2/stream.py", line 928, in receive_data
    self._track_content_length(len(data), end_stream)
  File "/Users/lewisa29/.pyenv/versions/3.5.1/lib/python3.5/site-packages/h2/stream.py", line 1083, in _track_content_length
    raise InvalidBodyLengthError(expected, actual)
h2.exceptions.InvalidBodyLengthError: InvalidBodyLengthError: Expected 11729 bytes, received 0
```

**Comment by Lukasa** [comment]
Yup, that's a hyper-h2 bug. We should aim to fix that. See #255.

**Comment by aidylewis** [comment]
Great. I'll look into fixing it.

**Comment by Lukasa** [comment]
FWIW, it'd also be useful to open the PR with the fixes to the example. =)

**Comment by Lukasa** [comment]
This got resolved as well. =)
