### ISSUE TITLE
Added TLS to sample program but gives "ssl.SSLError: [SSL: HTTP_REQUEST]"

### ISSUE THREAD

**Issue by laike9m** [python-hyper/hyper-h2#313]
So I was trying to modify the given [sample](https://github.com/python-hyper/hyper-h2/blob/master/docs/source/basic-usage.rst#section-6-bringing-it-all-together) to support HTTPS, here's the modified code:

```python
#!/usr/local/bin/python3

import http.server, ssl

import json
import socket

import h2.connection
import h2.events

def send_response(conn, event):
    stream_id = event.stream_id
    response_data = json.dumps(dict(event.headers)).encode('utf-8')

    conn.send_headers(
        stream_id=stream_id,
        headers=[
            (':status', '200'),
            ('server', 'basic-h2-server/1.0'),
            ('content-length', str(len(response_data))),
            ('content-type', 'application/json'),
        ],
    )
    conn.send_data(
        stream_id=stream_id,
        data=response_data,
        end_stream=True
    )

def handle(sock):
    conn = h2.connection.H2Connection(client_side=False)
    conn.initiate_connection()
    sock.sendall(conn.data_to_send())

    while True:
        data = sock.recv(65535)
        if not data:
            break

        events = conn.receive_data(data)
        for event in events:
            if isinstance(event, h2.events.RequestReceived):
                send_response(conn, event)

        data_to_send = conn.data_to_send()
        if data_to_send:
            sock.sendall(data_to_send)

certfile="path-to-self-signed-cert"
keyfile="path-to-key"

sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(('0.0.0.0', 8081))
sock.listen(5)

ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.options |= (
    ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1 | ssl.OP_NO_COMPRESSION
)
ssl_context.set_ciphers("ECDHE+AESGCM")
ssl_context.load_cert_chain(certfile=certfile, keyfile=keyfile)
ssl_context.set_alpn_protocols(["h2"])

while True:
    conn = sock.accept()[0]
    sslconn = ssl_context.wrap_socket(conn, server_side=True)
    handle(sslconn)
```

The ssl part of code is directly copied from the [asyncio sample](https://github.com/python-hyper/hyper-h2/blob/master/examples/asyncio/asyncio-server.py).

And below is the client code:
```python
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

from hyper import HTTPConnection

conn = HTTPConnection('localhost:8081')
conn.request('GET', '/')
resp = conn.get_response()

print(resp.read())
```

Running both, an error occurred on server side:
```bash
Traceback (most recent call last):
  File "/Users/yaoz/Dev/HTTP2/h2-https-server.py", line 68, in <module>
    sslconn = ssl_context.wrap_socket(conn, server_side=True)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:645)
```

Can't figure out why.

**Comment by Lukasa** [comment]
The answer is that you need to tell hyper to use TLS. By default it guesses whether to use TLS based on the port: if you use port 443 it uses TLS, otherwise it uses plaintext. If you change your line `conn = HTTPConnection('localhost:8081')` to `conn = HTTPConnection('localhost:8081', secure=True)` everything should start working.

**Comment by laike9m** [comment]
Yeah, adding `secure=True` eliminates that error. But it seems mocking `ssl._create_default_https_context` doesn't work and hyper still checks CA:
```bash
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:645)
```

**Comment by Lukasa** [comment]
Yeah, hyper-h2 configures its TLS contexts. You can patch the SSLContext in `hyper.tls._context`:

```python
hyper.tls._context.verify_mode = ssl.CERT_NONE
hyper.tls._context.check_hostname = False
```

**Comment by laike9m** [comment]
emmm, `hyper.tls._context` is `None`. Do I need to call [`init_context`](https://github.com/Lukasa/hyper/blob/development/hyper/tls.py#L71)?

**Comment by Lukasa** [comment]
Uh, yeah, sorry!

**Comment by Lukasa** [comment]
You'll also have to assign the return value to `hyper.tls._context`

**Comment by laike9m** [comment]
Cool, it works perfectly now. 😃
