### ISSUE TITLE
ImportError: cannot import name IntEnum

### ISSUE THREAD

**Issue by harry1064** [python-hyper/hyper-h2#351]
```
File "apnsClient.py", line 1, in <module>
    from hyper import HTTPConnection
  File "/usr/local/lib/python2.7/dist-packages/hyper/__init__.py", line 11, in <module>
    from .common.connection import HTTPConnection
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 10, in <module>
    from ..http20.connection import HTTP20Connection
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 8, in <module>
    import h2.connection
  File "/usr/local/lib/python2.7/dist-packages/h2/connection.py", line 10, in <module>
    from enum import Enum, IntEnum
ImportError: cannot import name IntEnum
```

I am using Python 2.7.

**Comment by harry1064** [comment]
`apt-xapian-index==0.44
chardet==2.0.1
command-not-found==0.2.44
enum==0.4.6
GnuPGInterface==0.3.2
h2==2.4.1
hpack==2.3.0
hyper==0.7.0
hyperframe==3.2.0
language-selector==0.1
python-apt===0.8.3ubuntu7
python-debian===0.1.21ubuntu1
ufw==0.31.1.post1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning`

**Comment by harry1064** [comment]
pip install enum34 solved the above issue but now i am getting this
`Traceback (most recent call last):
  File "apnsClient.py", line 1, in <module>
    from hyper import HTTPConnection
  File "/usr/local/lib/python2.7/dist-packages/hyper/__init__.py", line 11, in <module>
    from .common.connection import HTTPConnection
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 10, in <module>
    from ..http20.connection import HTTP20Connection
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 35, in <module>
    TRANSIENT_SSL_ERRORS = (ssl.SSL_ERROR_WANT_READ, ssl.SSL_ERROR_WANT_WRITE)
AttributeError: 'NoneType' object has no attribute 'SSL_ERROR_WANT_READ'`

**Comment by harry1064** [comment]
Installed Openssl version is 
`OpenSSL 1.0.1 14 Mar 2012`

**Comment by alexwlchan** [comment]
Glad the enum issue is sorted. SSL is very much not my area of expertise, but in Cory’s absence, I’ll have a look.

Which version of Python are you using? `python --version`

**Comment by harry1064** [comment]
`Python 2.7.3`

**Comment by alexwlchan** [comment]
So I think you need to run:

```console
$ pip install pyOpenSSL service_identity
```

---

Based on a look through the code:

* In `connection.py`, `ssl` is [imported from `compat.py`](https://github.com/Lukasa/hyper/blob/development/hyper/http20/connection.py#L12):

    ```python
    from ..compat import ssl
    ```

* Within `compat.py`, the value of `ssl` [depends on your Python version](https://github.com/Lukasa/hyper/blob/development/hyper/compat.py#L33):

    ```python
    if is_py2:
        if is_py2_7_9_or_later:
            import ssl
        else:
            ssl = ssl_compat
    ```

* And that `ssl_compat` variable gets defined [a few lines up](https://github.com/Lukasa/hyper/blob/development/hyper/compat.py#L13)

    ```python
    try:
        from . import ssl_compat
    except ImportError:
        # TODO log?
        ssl_compat = None
    ```

    So I’d guess that something in `ssl_compat` is throwing an ImportError, which would bubble up to give the error you’re seeing.

* In turn, looking in [`ssl_compat.py`](https://github.com/Lukasa/hyper/blob/development/hyper/ssl_compat.py), it talks about wrapping the pyOpenSSL API. I don’t see pyOpenSSL in your requirements.txt, but it’s in the hyper `setup.py`.

**Comment by harry1064** [comment]
Tried to install but i am getting this at the end of installation
` reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:18:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-SnlnXb/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-snchmN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-SnlnXb/cryptography/`

**Comment by alexwlchan** [comment]
You need to install the Python development headers for your platform. Probably something like:

```
apt-get install python-dev
brew install python-dev
yum install python-devel
```

**Comment by sigmavirus24** [comment]
@harry1064 you'll also need other development headers, e.g., `libssl-dev`. That said, Python 2.7.3 is absolutely ancient and subject to several CVEs. You should find a way to get a more up-to-date Python 2.7.

@alexwlchan there is no `python-dev` for brew. When you simply `brew install python` you get the headers, because brew is a more geared towards developers than apt and yum are.

**Comment by harry1064** [comment]
`File "apns2-python.py", line 6, in <module>
    res = c.get_response()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 129, in get_response
    return self._conn.get_response(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 203, in get_response
    self._sock.fill()
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/bufsocket.py", line 167, in fill
    count = self._sck.recv_into(self._buffer_view[self._buffer_end:])
  File "/usr/local/lib/python2.7/dist-packages/hyper/ssl_compat.py", line 159, in recv_into
    data = self.recv(bufsize, flags)
  File "/usr/local/lib/python2.7/dist-packages/hyper/ssl_compat.py", line 150, in recv
    flags
  File "/usr/local/lib/python2.7/dist-packages/hyper/ssl_compat.py", line 130, in _safe_ssl_call
    raise socket.error(e.args[0])
IndexError: tuple index out of range`

**Comment by Lukasa** [comment]
That exception is somewhat odd. It seems like you're encountering an error, but that error has no error string: in fact, it was raised without arguments. This can happen, but it's not likely. Can you run the script under `pdb` and tell me what the value of `e` is please?

**Comment by Lukasa** [comment]
Closing due to inactivity.
