### ISSUE TITLE
tornado example error

### ISSUE THREAD

**Issue by zii** [python-hyper/hyper-h2#397]
I run the tornado example, and view by chrome, it errored.
I installed openssl 1.0.2j, compile python 2.7.12 from source.
Can you help me to run it on chrome?

```
root@deb0:~/py/h2/tornado# python tornado-server.py
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fbc17077cb0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 276, in <lambda>
    self.io_loop.add_future(future, lambda f: f.result())
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "tornado-server.py", line 38, in handle_stream
    yield handler.handle()
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "tornado-server.py", line 50, in handle
    yield self.stream.write(self.conn.data_to_send())
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
StreamClosedError: Stream is closed
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fbc1702a4c8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 276, in <lambda>
    self.io_loop.add_future(future, lambda f: f.result())
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "tornado-server.py", line 38, in handle_stream
    yield handler.handle()
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "tornado-server.py", line 61, in handle
    self.request_received(event.headers, event.stream_id)
  File "tornado-server.py", line 80, in request_received
    self.conn.send_headers(stream_id, response_headers)
  File "/usr/local/lib/python2.7/site-packages/h2/connection.py", line 803, in send_headers
    headers, self.encoder, end_stream
  File "/usr/local/lib/python2.7/site-packages/h2/stream.py", line 788, in send_headers
    headers, encoder, hf, hdr_validation_flags
  File "/usr/local/lib/python2.7/site-packages/h2/stream.py", line 1119, in _build_headers_frames
    encoded_headers = encoder.encode(headers)
  File "/usr/local/lib/python2.7/site-packages/hpack/hpack.py", line 229, in encode
    for header in headers:
  File "/usr/local/lib/python2.7/site-packages/h2/utilities.py", line 302, in _reject_pseudo_header_fields
    for header in headers:
  File "/usr/local/lib/python2.7/site-packages/h2/utilities.py", line 271, in _reject_connection_header
    for header in headers:
  File "/usr/local/lib/python2.7/site-packages/h2/utilities.py", line 255, in _reject_te
    for header in headers:
  File "/usr/local/lib/python2.7/site-packages/h2/utilities.py", line 69, in _secure_headers
    for header in headers:
  File "/usr/local/lib/python2.7/site-packages/h2/utilities.py", line 437, in _strip_surrounding_whitespace
    yield (header[0].strip(), header[1].strip())
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by Lukasa** [comment]
The problem is simple: on line 77 we call `len(data)`. It should be changed to `str(len(data))`.

**Comment by zii** [comment]
Thank you so quickly!
